### PR TITLE
Minor documentation wording fix

### PR DESCRIPTION
**Pull request by lolli42**

### CODE REVIEW

**Review by ctalledo — APPROVED** [review]
Thanks! Could you please commit with "git commit --signoff" so that our automated checks pass?

Thank you very much for catching the typo.

**Review by rodnymolina — COMMENTED** [review]
@lolli42, thanks for your contribution.

Can you please sign your commit and push it again?

```
git commit --amend --signoff
```

**Comment by lolli42** [comment]
You're quick :)
Was on the DCO already when the checks mumbled. Hope this is fine now ;)

**Review by ctalledo — COMMENTED** [review]
Also, if you add "[skip ci]" to the commit title, it will bypass the build process.

**Comment by lolli42** [comment]
Note: Special thanks not only for the very quick merge, but for excellent docs and blog posts!
They're really boosting my knowledge at the moment.
I need that for a transition of a dockerized DooD based multi-bamboo-agent CI pipeline to either gitlab or maybe drone ... so I know the headaches with DooD volumes and bind-mounts (been there, done that, it's awful) and the security implications (for an open source project) and I'm now considering to play around with sysbox to see if it fits and solves our needs.
I may contact you later if this turns out to be a good use-case, if this is fine with you.

**Comment by ctalledo** [comment]
Thanks @lolli42 for giving Sysbox a shot! Let us know of any questions or improvements we can make. 

Another good way to reach us is via our [Slack workspace](https://nestybox-support.slack.com/join/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ#/). 

Thanks again!

**Pull request merged**
