### PR TITLE
Add tests for recently fixed container restart issues

### PR DESCRIPTION
**Pull request by joanbm**
Tests for recently fixed container restart issues. See PR nestybox/sysbox-mgr#29

### CODE REVIEW

**Review by rodnymolina — APPROVED** [review]
LGTM.

Excellent work. Thanks Joan!

**Review by ctalledo — APPROVED** [review]
Looks great, thanks!

**Comment by ctalledo** [comment]
FYI, the CI is expected to fail until the changes to the sub-repo (e.g., sysbox-mgr) are submitted and the pointer to the sub-repo is updated. 

If the tests pass in your local machine, then please commit the changes to the sub-repo first, and then you add to this current PR a commit of the subrepo (e.g., git add sysbox-mgr && git commit --signoff -m "[sysbox-mgr] Updating submodule"). 

This way, the CI will trigger again but this time it will find the changes in the sub-repo, thus causing the newly added tests to run on top of your latest changes.

Hope that makes sense :)

**Comment by joanbm** [comment]
PR updated with the submodule references, so the CI build works (I wasn't sure it would work since the submodule is still referring to your repository URL, but it actually works).

**Comment by rodnymolina** [comment]
> PR updated with the submodule references, so the CI build works (I wasn't sure it would work since the submodule is still referring to your repository URL, but it actually works).

Yes, it will work, git-submodules are that flexible! Problem with this workflow, in the best-case scenario, is that you may end up running the Sysbox CI for every partial change that you make to any of the Sysbox submodules. In the worst-case, you could end up committing these changes into the Sysbox's (superproject) master branch, while still having the incorrect/incomplete changes in the Sysbox inner submodules (i.e. submodule pointers are not fully updated).

So i would suggest to update the Sysbox submodule pointers only after the corresponding changes in those submodules have been merged into the submodule's master branches. And only then, i would update the superproject pointers. This is the workflow that we typically follow.

Hope it makes sense.

**Comment by joanbm** [comment]
Great! Just a note, I've noticed this repository now points to e.g. nestybox/sysbox-mgr@fac681accd021fecc74687943e8dbe45b917f2b5, but the master branch of nestybox/sysbox-mgr points to nestybox/sysbox-mgr@c04ffe1732e17e7b9171c872c438b2122dccdcec (which are actually the same diff, but with a different commiter). Not sure if that's what you wanted.

**Comment by rodnymolina** [comment]
Thanks for double-checking; i just fixed it. This is probably just a side-effect of what i mentioned above.

**Pull request merged**
